### ISSUE TITLE
Substrate Utilities - SCALE Decoder

### ISSUE THREAD

**Issue by lucgerrits** [shawntabrizi/substrate-js-utilities#1]
Hi,
The SCALE Decoder looks useful but I can't make it work. I'm trying to decode Substrate metadata (V12).
I get a long array of numbers, I'm not sure what to think about it.
I don't know exactly what to put in the custom types.

Do you have any suggestions?

-Luc

**Comment by shawntabrizi** [comment]
SCALE Decoder does not automatically know what you want to decode. You must provide it the types and structures you need.

The metadata type is very complex, and there are easier ways to retrieve it using Polkadot JS:

```
const data = await api.rpc.state.getMetadata()
```

What is it you are trying to do specifically?

**Comment by lucgerrits** [comment]
I see. Well, my goal is to decode metadata for [polkadot_api_cpp](https://github.com/usetech-llc/polkadot_api_cpp) . The issue https://github.com/usetech-llc/polkadot_api_cpp/issues/32 resume my situation.

**In short**: polkadot_api_cpp has metadata maintained up to V6 (see [here](https://github.com/usetech-llc/polkadot_api_cpp/blob/8b72b4e7c4662e45cde6f7a4b7bf7fad55770505/src/application.cpp#L448)), and I'm trying to use the polkadot_api_cpp for metadata V12. I need to be in C++ because my goal is to implement it on a small (or even very small) IoT.

Your tool could maybe help me to understand better the metadata structure to code the V12 in polkadot_api_cpp. But it doesn't seem easy!!

**Comment by shawntabrizi** [comment]
Yeah I dont think my utility will help you here, but check out:

https://github.com/polkadot-js/api/tree/master/packages/metadata/src

and

https://github.com/paritytech/substrate/blob/master/frame/metadata/src/lib.rs#L392
